VIT Assignment-1

TASK-1

Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame([[19,44,"M",6000],[20,45,"F",6500],[25,np.nan,"M",5500],[np.nan,60,"F",5000]])
df

      0     1  2     3
0  19.0  44.0  M  6000
1  20.0  45.0  F  6500
2  25.0   NaN  M  5500
3   NaN  60.0  F  5000

TASK-2

Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [ ]:
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
df

   Random value 1  Random value 2 Random value 3  Random value 4
0            19.0            44.0              M            6000
1            20.0            45.0              F            6500
2            25.0             NaN              M            5500
3             NaN            60.0              F            5000

TASK-3

Find the descriptive statistics of the 'df' dataframe

In [ ]:
df.describe()

       Random value 1  Random value 2  Random value 4
count        3.000000        3.000000        4.000000
mean        21.333333       49.666667     5750.000000
std          3.214550        8.962886      645.497224
min         19.000000       44.000000     5000.000000
25%         19.500000       44.500000     5375.000000
50%         20.000000       45.000000     5750.000000
75%         22.500000       52.500000     6125.000000
max         25.000000       60.000000     6500.000000

TASK-4

check for the null values

In [ ]:
df.isnull().any()

Random value 1     True
Random value 2     True
Random value 3    False
Random value 4    False
dtype: bool

In [ ]:
df.isnull().sum()

Random value 1    1
Random value 2    1
Random value 3    0
Random value 4    0
dtype: int64

finding datatypes of columns

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  3 non-null      float64
 1   Random value 2  3 non-null      float64
 2   Random value 3  4 non-null      object
 3   Random value 4  4 non-null      int64
dtypes: float64(2), int64(1), object(1)
memory usage: 256.0+ bytes

TASK-5

Display the 'Random value 2' & 'Random value 3' columns with location method

In [ ]:
df.loc[:,['Random value 2','Random value 3']]

   Random value 2 Random value 3
0            44.0              M
1            45.0              F
2             NaN              M
3            60.0              F

Display the 'Random value 2' & 'Random value 3' columns with index location method

In [ ]:
df.iloc[: ,[1,2]]

   Random value 2 Random value 3
0            44.0              M
1            45.0              F
2             NaN              M
3            60.0              F

END

THANK YOU